config/routes.rb
Rails.application.routes.draw do
  root to: 'todo_lists#index'

  get '/register', to: 'groups#new', as: :register_group
  post '/register', to: 'groups#create'
  get '/groups/:id', to: 'groups#edit', as: :edit_group
  patch '/groups/:id', to: 'groups#update'
  delete '/groups/:id', to: 'groups#destroy'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :groups do
    resources :members, except: :index
    resources :todo_lists
  end

  resources :todo_lists do
    resources :todo_items 
  end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  has_many :members, through: :member_todo_items
  has_many :member_todo_items, dependent: :destroy

  validates :name,
    presence: true,
    length: { minimum: 3, maximum: 40 }
  validates_date :start_date
  validates_date :end_date, after: :start_date
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  def new
    @todo_item = @todo_list.todo_items.new
    render 'form_modal'
  end

  def create
    @todo_item = @todo_list.todo_items.build(todo_item_params)

    if !@todo_item.save
      render json: @todo_item.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

  def edit
    render 'form_modal'
  end

  def update
    if !@todo_item.update_attributes(todo_item_params)
      render json: @todo_item.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

  def destroy
    if !@todo_item.destroy
      flash[:danger] = 'Ooops, etwas ist schiefgegangen, bitte kontaktiere den_die Administrator_in!!'
    end
  end

  private

  def todo_item_params
    params.require(:todo_item).permit(:name, :description, :start_date, :end_date, :completed)
  end

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h2.modal-title= @todo_item.name || 'New todo item'
    = form_for [@todo_list, @todo_item], remote: true do |f|
      .modal-body
        .row
          .col-xs-12
            = f.text_field :name, placeholder: 'Name', class: 'form-control'
          .col-xs-6
            = f.text_field :start_date, placeholder: 'Start', class: 'form-control'
          .col-xs-6
            = f.text_field :end_date, placeholder: 'End', class: 'form-control'
          .col-xs-12
            = f.text_area :description, placeholder: 'Description', class: 'form-control'
      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Schließen
        = f.submit 'Save', class: 'btn btn-success'

app/views/todo_items/_todo_item.html.haml
%li.todo-item{todo_item_id: item.id}
  = item.name
  = link_to edit_todo_list_todo_item_path(id: item.id, todo_list_id: item.todo_list_id), remote: true do
    .fa.fa-edit
  = link_to todo_list_todo_item_path(id: item.id, todo_list_id: item.todo_list_id), method: :delete, data: { :confirm => 'Are you sure?' }, remote: true do
    .fa.fa-trash-o
  %br
  %i.todo-item-description= item.description

app/views/todo_items/create.js.erb
var todoListDiv = jQuery('.panel[todo_list_id=<%= @todo_item.todo_list_id %>]');
todoListDiv.find('.todo-items').append("<%= j render partial: 'todo_item', locals: {item: @todo_item} %>");

app/views/todo_items/destroy.js.erb
var todoItemDiv = jQuery('li[todo_item_id=<%= @todo_item.id %>]');
todoItemDiv.fadeOut();

app/views/todo_items/form_modal.js.erb
jQuery("#form-modal").html("<%= escape_javascript(render 'todo_items/form') %>").modal('show');

app/views/todo_items/update.js.erb
var todoItemDiv = jQuery('li[todo_item_id=<%= @todo_item.id %>]');
todoItemDiv.replaceWith("<%= j render partial: 'todo_item', locals: {item: @todo_item} %>");