config/routes.rb
Rails.application.routes.draw do
  root to: 'todo_lists#index'

  get '/register', to: 'groups#new', as: :register_group
  post '/register', to: 'groups#create'
  get '/groups/:id', to: 'groups#edit', as: :edit_group
  patch '/groups/:id', to: 'groups#update'
  delete '/groups/:id', to: 'groups#destroy'

  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :groups do
    resources :members, except: :index
    resources :todo_lists
  end

  resources :todo_lists do
    resources :todo_items 
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items, dependent: :destroy

  validates :name,
    presence: true,
    length: { minimum: 3, maximum: 40 }
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :check_if_signed_in
  before_action :scope_to_current_group
  before_action :get_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = @group.todo_lists.all
  end

  def new
    @todo_list = @group.todo_lists.new
    render 'form_modal'
  end

  def edit
    @todo_list = @group.todo_lists.find(params[:id])
    render 'form_modal'
  end

  def create
    @todo_list = @group.todo_lists.build(todo_list_params)
    if !@todo_list.save
      render json: @todo_list.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

  def update
    if !@todo_list.update_attributes(todo_list_params)
      render json: @todo_list.errors.full_messages.to_sentence, status: :unprocessable_entity
    end
  end

  def destroy
    if !@todo_list.destroy
      flash[:danger] = 'Ooops, etwas ist schiefgegangen, bitte kontaktiere den_die Administrator_in!!'
    end
  end

  private

  def get_todo_list
    @todo_list = @group.todo_lists.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:name, :description)
  end
end

app/views/todo_lists/_form.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", :type => "button"} ×
      %h2.modal-title= @todo_list.name || 'New todo list'
    = form_for @todo_list, remote: true do |f|
      .modal-body
        .row
          .col-xs-12
            = f.text_field :name, placeholder: 'Name', class: 'form-control'
          .col-xs-12
            = f.text_area :description, placeholder: 'Description', class: 'form-control'
      .modal-footer
        %button.btn.btn-default{'data-dismiss' => 'modal', type: 'button'} Schließen
        = f.submit 'Save', class: 'btn btn-success'

app/views/todo_lists/_todo_list.html.haml
.panel.panel-default{todo_list_id: list.id}
  .panel-heading
    %h4.panel-title
      %a.accordion-toggle{'data-parent' => '#accordion-panel', 'data-toggle' => 'collapse', href: "\##{list.id}"}
        %b.todo-list-name= list.name
        .pull-right
          = link_to edit_todo_list_path(list), remote: true do
            .fa.fa-edit
          = link_to list, method: :delete, data: { :confirm => 'Are you sure?' }, remote: true do
            .fa.fa-trash-o
  .panel-collapse.collapse{id: list.id}
    .panel-body
      %i.todo-list-description= list.description
      %hr
      %ul.todo-items
        - list.todo_items.each do |item|
          = render 'todo_items/todo_item', item: item
      = link_to new_todo_list_todo_item_path(todo_list_id: list.id), remote: true do
        .fa.fa-plus-square
        New item

app/views/todo_lists/create.js.erb
jQuery('#accordion-panel').prepend("<%= j render partial: 'todo_list', locals: {list: @todo_list} %>");

app/views/todo_lists/destroy.js.erb
var todoListDiv = jQuery('.panel[todo_list_id=<%= @todo_list.id %>]');
todoListDiv.fadeOut();

app/views/todo_lists/form_modal.js.erb
jQuery("#form-modal").html("<%= escape_javascript(render 'todo_lists/form') %>").modal('show');

app/views/todo_lists/index.html.haml
.row
  .col-xs-12
    %h1 To Do Lists

    = link_to new_todo_list_path, remote: true do
      .fa.fa-plus-square
      New todo list

  .col-xs-12
    #accordion-panel.panel-group
      - @todo_lists.sort_by(&:created_at).reverse.each do |list|
        = render 'todo_list', list: list

app/views/todo_lists/update.js.erb
var todoListDiv = jQuery('.panel[todo_list_id=<%= @todo_list.id %>]');
todoListDiv.html("<%= j render partial: 'todo_list', locals: {list: @todo_list} %>");